{% set name = "scikit-bio" %}
{% set version = "0.5.6" %}
{% set sha256 = "48b73ec53ce0ff2c2e3e05f3cfcf93527c1525a8d3e9dd4ae317b4219c37f0ea" %}
{% set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - scikit-bio-pr-1719-backport.patch
    - scikit-bio-pr-1720-backport.patch
    # See: https://github.com/biocore/scikit-bio/issues/1757
    - skip-broken-tests.patch   # [py > 36]

build:
  # non-x86 (currently) not supported due to SSE intrinsics use
  skip: true  # [win or py2k or not x86]
  number: {{ build_num }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy-devel {{ numpy }}
  run:
    - python
    - lockfile >=0.10.2
    - cachecontrol >=0.11.5
    - decorator >=3.4.2
    - ipython >=3.2.0
    - matplotlib-base >=1.4.3
    - natsort >=4.0.3
    - pandas >=1.0.0
    - scipy >=1.3.0
    - scikit-learn >=0.19.1
    - hdmedians >=0.13
    - pytest

test:
  imports:
    - skbio
    - skbio.alignment
    - skbio.alignment._lib
    - skbio.alignment.tests
    - skbio.diversity
    - skbio.diversity.alpha
    - skbio.diversity.alpha.tests
    - skbio.diversity.beta
    - skbio.diversity.beta.tests
    - skbio.diversity.tests
    - skbio.io
    - skbio.io.format
    - skbio.io.format.tests
    - skbio.io.tests
    - skbio.sequence
    - skbio.sequence.tests
    - skbio.stats
    - skbio.stats.distance
    - skbio.stats.distance.tests
    - skbio.stats.evolve
    - skbio.stats.evolve.tests
    - skbio.stats.ordination
    - skbio.stats.ordination.tests
    - skbio.stats.tests
    - skbio.tests
    - skbio.tree
    - skbio.tree.tests
    - skbio.util
    - skbio.util.tests
  commands:
    - MPLBACKEND='Agg' python -m skbio.test

about:
  home: http://scikit-bio.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: 'Data structures, algorithms and educational resources for bioinformatics.'
  description: |
    scikit-bio is an open-source, BSD-licensed, python package providing data
    structures, algorithms, and educational resources for bioinformatics.
  doc_url: http://scikit-bio.org
  doc_source_url: https://github.com/biocore/scikit-bio/blob/master/doc/source/index.rst
  dev_url: https://github.com/biocore/scikit-bio

extra:
  recipe-maintainers:
    - ebolyen
    - wasade
    - mortonjt
    - thermokarst
    - ElDeveloper
    - chenghlee
