{% set name = "scikit-bio" %}
{% set version = "0.5.5" %}
{% set sha256 = "TBD" %}
{% set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/biocore/scikit-bio.git
  git_rev: 0.5.5

build:
  skip: true  # [win or py2k]
  number: {{ build_num }}
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - cython
    - numpy 1.9.*
  run:
    - python
    - lockfile >=0.10.2
    - cachecontrol >=0.11.5
    - decorator >=3.4.2
    - ipython >=3.2.0
    - matplotlib >=1.4.3
    - natsort >=4.0.3
    - numpy >=1.9.2
    - pandas >=0.19.2
    - scipy >=0.15.1
    - pytest
    - scikit-learn >=0.19.1
    - hdmedians >=0.13    

test:
  imports:
    - skbio
    - skbio.alignment
    - skbio.alignment._lib
    - skbio.alignment.tests
    - skbio.diversity
    - skbio.diversity.alpha
    - skbio.diversity.alpha.tests
    - skbio.diversity.beta
    - skbio.diversity.beta.tests
    - skbio.diversity.tests
    - skbio.io
    - skbio.io.format
    - skbio.io.format.tests
    - skbio.io.tests
    - skbio.sequence
    - skbio.sequence.tests
    - skbio.stats
    - skbio.stats.distance
    - skbio.stats.distance.tests
    - skbio.stats.evolve
    - skbio.stats.evolve.tests
    - skbio.stats.ordination
    - skbio.stats.ordination.tests
    - skbio.stats.tests
    - skbio.tests
    - skbio.tree
    - skbio.tree.tests
    - skbio.util
    - skbio.util.tests
  commands:
    - python -m skbio.test  # [not linux]
    - MPLBACKEND='Agg' python -m skbio.test  # [linux]

about:
  home: http://scikit-bio.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: 'Data structures, algorithms and educational resources for bioinformatics.'
  doc_url: http://scikit-bio.org
  dev_url: http://github.com/biocore/scikit-bio

extra:
  recipe-maintainers:
    - ebolyen
    - wasade
    - mortonjt
