# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_NPY=110  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=110  CONDA_PY=34
    - CONDA_NPY=111  CONDA_PY=34
    - CONDA_NPY=110  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RE24Ed5zdBMQW+UXPapscTifpW1rLDg6+uvDfjfATeYJ156c4DfDV+v0cxzCWQDU+aiS8t5mmFzL8b/g4220x3AZjFQlzA5cpl129a4c3FP8SnKIhjsUfj1XevQKfTIUSbMeeltqlxVI9GaqICsiuE21Y8sC7w30B83PZ1Qj4j7Bi8T1v12ijB9GxBrSqmp+NT/FOoTcCo7dnuBA9mxlOv0PX9ZGMmlahjeOWPuZpVnu1lFZqMYyxn9Xye3JURJF5S0XSSewn8nPCqmWb8Y/3uEim5aDAcXcULSgj+x7hf0wkn+z3xi6XhnHAqwTzxrix120De0rcFz8JHmnHAo7mKXaPD3Riszm9j83eJ1mUSq5i7g1Z9hhri5oj8ZKV+tDIX/Zdmmi0rzSRDEaO8ODvmBS7mUu8/t+WE18UU03SFvwP5PQSDigwat6rvWYQBNY6oAOT0LX92LpZC5N9/FgXzFmhyZFaZiWgx7GfUArPQB/Z8KyYlZ/WSVPGDm3ki3OLfpDWkh39aEG+o6ieFXjWqYsiZnp71oCXMN/ePXF5/0b3Fffg+FbRRqzxX7d1ccwKm31EvQfDXs6/2yn7NgsIIfTe2HcMD14zAnPIjt+s+mI+l+5gY2gWzhcrPvo3Tw0sp4bevJ4XicGZNiGEUg+e4lEs0dI1yCSKIfNqOnBhcw="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
