travis:
  secure:
    BINSTAR_TOKEN: i66GNe7gAvNNmT18mAcgGVlc0NJvs6UbKR70INnz4m0bh+VduPIkQHsRNum2iei7KBIpUVd4F6bpEFJAcFpSnV//xzvxLQgVFsDR0dAlyPFYqNuGcG086fgzb5coPJhFbNMVFLjoX3Vt/wxt8bK2yHiIldD/va/niQq9czBZNFdFNq5ccNqrWs8a3doTCnVrPjHaHhmc/y6nD53qppKXai86RDduqRE6SnuRtuMKerBnzp3buWK03joRVD5IR0qWObiFbp3A3XVYmlXTZYkkst7QLSG6N53iMCRGjifes1ilUU3cGEKGA5AVzaIub7d/CS+sdxh9wSqC6IkylPCw/wFmBRdDqf9cCNCggUbfTC2UuXp9xJGH1ki8dRR1tIlhyxnbyB1VuybFkAU2YRaPDCSdTi2oD/7PbksMmUMVG+CFiKXEV/4Wja6FS6xHKqIf+Zm1ikq/xVOje78t4gC0YOHxyWK2GyZ23/jfefRFayvuFpAdsgZEubedOmtpHcbp9gmUpxLzaECPFVWGebtuIjsUv8pDsglzdqUg96yS81z60gYEo+JEKUWWjNiS8kcQSXxZcnTGJ4TmRF1qrPApA9rLCSspmFGd/dCEhCCyoIFcZoCmC2L9LwshFddoR2FgD6xh3B9Dr1264p/UbTYaChPwH3CeC0vMrtDO3nyVx3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
