travis:
  secure:
    BINSTAR_TOKEN: RE24Ed5zdBMQW+UXPapscTifpW1rLDg6+uvDfjfATeYJ156c4DfDV+v0cxzCWQDU+aiS8t5mmFzL8b/g4220x3AZjFQlzA5cpl129a4c3FP8SnKIhjsUfj1XevQKfTIUSbMeeltqlxVI9GaqICsiuE21Y8sC7w30B83PZ1Qj4j7Bi8T1v12ijB9GxBrSqmp+NT/FOoTcCo7dnuBA9mxlOv0PX9ZGMmlahjeOWPuZpVnu1lFZqMYyxn9Xye3JURJF5S0XSSewn8nPCqmWb8Y/3uEim5aDAcXcULSgj+x7hf0wkn+z3xi6XhnHAqwTzxrix120De0rcFz8JHmnHAo7mKXaPD3Riszm9j83eJ1mUSq5i7g1Z9hhri5oj8ZKV+tDIX/Zdmmi0rzSRDEaO8ODvmBS7mUu8/t+WE18UU03SFvwP5PQSDigwat6rvWYQBNY6oAOT0LX92LpZC5N9/FgXzFmhyZFaZiWgx7GfUArPQB/Z8KyYlZ/WSVPGDm3ki3OLfpDWkh39aEG+o6ieFXjWqYsiZnp71oCXMN/ePXF5/0b3Fffg+FbRRqzxX7d1ccwKm31EvQfDXs6/2yn7NgsIIfTe2HcMD14zAnPIjt+s+mI+l+5gY2gWzhcrPvo3Tw0sp4bevJ4XicGZNiGEUg+e4lEs0dI1yCSKIfNqOnBhcw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
